### ISSUE TITLE
Total number of tests is greater when running with --run_test=* option

### ISSUE THREAD

**Issue by k15tfu** [boostorg/test#135]
I have a Boost.Test project with 8772 test cases but today I spent a few hours trying to find ONE test which is not run on our build server because when I run it locally with --run_test=* the number of tests is greater by 1.

Why?

**Comment by raffienficiaud** [comment]
You may output all tests in your local machine and the test running by just running ``--list_content`` instead, and outputting to a file. Use a diff for comparing those 2 files afterwards, and let me know about your findings.

**Comment by k15tfu** [comment]
They are the same O_o

```
...\x64.test.dbg>BoostTests.exe --run_test=*
Running 8773 test cases...
^C
...\x64.test.dbg>BoostTests.exe --run_test=* --list_content 1>with.log 2>&1
...\x64.test.dbg>BoostTests.exe
Running 8772 test cases...
^C
...\x64.test.dbg>BoostTests.exe --list_content 1>without.log 2>&1
.../x64.test.dbg$ diff with.log without.log
.../x64.test.dbg$
```

**Comment by k15tfu** [comment]
Ahh. --list_content ignores --run_test filter.

**Comment by k15tfu** [comment]
I have checked that there are really 8773 test cases in log files.

**Comment by k15tfu** [comment]
Okay, I found. --run_test=* also runs the disabled test cases.

Probably it's an expected behavior.

**Comment by raffienficiaud** [comment]
I'll add a comment in the doc. Thanks.
