### ISSUE TITLE
Support for Boost.MP11 and Boost.Hana type lists?

### ISSUE THREAD

**Issue by rhalbersma** [boostorg/test#141]
`BOOST_AUTO_TEST_CASE_TEMPLATE` uses Boost.MPL's machinery (in particular: `boost::mpl::for_each`) to automate tests cases over type lists. However, Boost.MPL is not compatible with the modern Boost.MP11 and Boost.Hana type lists, firing `BOOST_MPL_ASSERT(( is_sequence<Sequence> ));` when passing an `mp11::mp_list` or a `hana::tuple` instead of an `mpl::vector`. 

Is it possible to swap out the Boost.MPL implementation for Boost.MP11? I think Boost.MP11 uses only pattern matching on variadic parameter packs to determine if something is a type list, so it should be backward compatible with existing code that passes `mpl::vector` as type lists, or even with Boost.Hana (or `std::tuple`) type lists. To accomodate C++98 users, using an MP11 implementation can be done conditionally on the compiler version.

**Comment by raffienficiaud** [comment]
Indeed, we can easily remove the use of `mpl` in this case (sorry for the delayed answer).

**Comment by kedarbhat** [comment]
Both mp11 and Hana provide facilities for use with MPL/Fusion: [Godbolt Compiler Explorer Example](https://gcc.godbolt.org/z/3nAGcE)

**Comment by raffienficiaud** [comment]
I have a possible implementation in the branch `topic/GH-141-mp11-hana-typelist`. Would you please give a try? The signature of the test declaration does not change.

**Comment by raffienficiaud** [comment]
+CC @tonyelewis

**Comment by raffienficiaud** [comment]
In master, should be in 1.70.
