### ISSUE TITLE
Unable to compile boost/test for C++17

### ISSUE THREAD

**Issue by k15tfu** [boostorg/test#146]
```
clang-linux.compile.c++.without-pth bin.v2/linux.static.x64/boost/bin.v2/libs/test/build/clang-linux-6.0.0/release/link-static/threading-multi/debug.o
In file included from libs/test/src/debug.cpp:16:
In file included from ./boost/test/impl/debug.ipp:53:
./boost/test/utils/algorithm.hpp:118:42: error: no member named 'bind1st' in namespace 'std'
        if( std::find_if( first2, last2, BOOST_TEST_BIND1ST( pred, *first1 ) ) == last2 )
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./boost/test/utils/algorithm.hpp:25:38: note: expanded from macro 'BOOST_TEST_BIND1ST'
#define BOOST_TEST_BIND1ST(F,A) std::bind1st( (F), (A) )
```

**Comment by raffienficiaud** [comment]
Please file an issue on Trac, see the contribution file.

**Comment by k15tfu** [comment]
https://svn.boost.org/trac10/ticket/13574

**Comment by jeking3** [comment]
I am running into this while trying to add CI support.  The Visual Studio 2017 jobs with cxxstd=17 or cxxstd=latest are failing because of this...

**Comment by jeking3** [comment]
It's an easy fix.

**Comment by raffienficiaud** [comment]
Boost.test uses [BOOST_NO_CXX98_BINDERS](https://www.boost.org/doc/libs/1_67_0/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.macros_that_describe_features_that_have_been_removed_from_the_standard_), so it should work. What is the fix that you are referring to?

**Comment by raffienficiaud** [comment]
Also, I use `b2 --abbreviate-paths address-model=64 toolset=msvc-14.1 cxxflags="/std:c++latest"` for my VS 2017 CI.

**Comment by jeking3** [comment]
The issue I found was in the example code - the other instances seem to have been resolved.

**Comment by raffienficiaud** [comment]
Closing this one and working on #182 instead

**Comment by k15tfu** [comment]
Thank you! I see that it works with C++17 now.
