### ISSUE TITLE
Catch block for boost::exception appears after std::exception in execution_monitor::execute()

### ISSUE THREAD

**Issue by k15tfu** [boostorg/test#147]
So, if I throw myexception defined as `struct myexception : std::exception, virtual boost::exception` it prints uninformative message

**Comment by k15tfu** [comment]
If you prefer to use Boost Trac why you haven't disabled Issues tab on GitHub?

```
using error_code = boost::error_info<struct tag_error_code, uint32_t>;
struct myexception : std::exception, virtual boost::exception {};

BOOST_AUTO_TEST_CASE(is_always_lock_free) {
  BOOST_THROW_EXCEPTION(myexception << error_code(123));
}
```

At the moment the exception will be catch as `std::exception`:
```
c:\p\dotnet-products\2\dotcommon\native\solution\common.boosttest\src\mmstorage_v2\storage_test.cpp(66): fatal error: in "void __cdecl `anonymous-namespace'::mmstorage_v2::storage::create_storage_with_file_handle::test_method(void)": class boost::exception_detail::clone_impl<struct jb::mms::exception::create_mapping>: Unknown exception
```

Well.. I swapped the boost::exception && std::exception and the only difference was in showing "Unknown exception" message.  Sorry, thought it will use boost::diagnostic_information() instead of unknown-exception phrase.

But isn't it right to catch more narrowed (non generic) exceptions first?

**Comment by raffienficiaud** [comment]
What happens if you derive only from `std::exception`? and recently Trac has been closed to new tickets.

**Comment by raffienficiaud** [comment]
In develop, closing.

**Comment by k15tfu** [comment]
Tested, thanks!
