### ISSUE TITLE
Testing the main() function

### ISSUE THREAD

**Issue by pinventado** [boostorg/test#155]
I'm trying to adopt a test-driven approach for my introductory programming class where our first topics are on variable declarations, using cout, simple conditions, and loops. Students don't know how to use functions yet, so I was wondering if it was possible to run a unit test on main.

I've seen a couple of discussions that suggest ways to grab data from cout ([see accepted answer](https://stackoverflow.com/questions/5405016/can-i-check-my-programs-output-with-boost-test)) that then allow testing, but the issue is that students' programs never really call functions. I don't know how to call the main function from the unit test, if that's even possible. Here's sample code of the types of programs students make to give some context.

```cpp
#include <iostream>
using namespace std;

int main()
{
  int num1;
  int num2;
  cout << "Please enter the first number: ";
  cin >> num1;
  cout << "Please enter the second number: ";
  cin >> num2;
  cout << "The sum of " << num1 << " and " << num2 << " is " << num1 + num2 << endl;
  return 0;
}
```

**Comment by pinventado** [comment]
Your first suggestions makes a lot of sense, but I hesitate to introduce students to unit testing right away. It might be too much for them to process and it's not really the focus of the course.

Your second suggestion seems more plausible because `assert` shouldn't be too difficult to understand and is a good introduction to unit tests.

Aside from using `assert`, I'm still searching for other alternatives to do unit testing without getting students to create functions. I'm thinking that students can run a script or `make` that runs the unit test without them having to add anything outside of our usual discussions to their code.

**Comment by tiendq** [comment]
Why don't just move code inside `main` into normal functions and unit tested them as usual?

**Comment by pinventado** [comment]
I'm teaching an introductory programming course and want to use unit tests to help students get immediate feedback. The way it's taught is that functions are introduced later. In that case, I won't be able to do unit testing until then.

So, I'm trying to see if I can get that effect of unit testing without the extra requirement of having to use functions yet.

**Comment by raffienficiaud** [comment]
@pinventado I am closing the issue. If you need more help, please open a new ticket. 
Thanks!
