### ISSUE TITLE
close_at_tolerance always returns false for comparisons of infinity

### ISSUE THREAD

**Issue by Timmmm** [boostorg/test#156]
Consider this code:

```
#include <boost/test/tools/floating_point_comparison.hpp>
#include <iostream>
#include <limits>

namespace fpc = boost::math::fpc;
int main() {
	float a = std::numeric_limits<float>::infinity();
	float b = std::numeric_limits<float>::infinity();

	auto P = fpc::close_at_tolerance<float>(fpc::percent_tolerance<float>(0.01), fpc::FPC_WEAK);
	std::cout << P(a, b) << "\n";
}
```

It prints `0`. You might say "well that makes sense because one infinity is not the same as another". Except that the IEEE floating point standard considers `inf == inf` to be true, which means that you have the strange situation where this passes:

```
BOOST_AUTO_TEST_CASE(foo)
) {
	float a = std::numeric_limits<float>::infinity();
	float b = a;
	BOOST_TEST(a == b);
}
```

But this does not:

```
BOOST_AUTO_TEST_CASE(foo,
	*utf::tolerance<float>(fpc::percent_tolerance<float>(0.01))
) {
	float a = std::numeric_limits<float>::infinity();
	float b = a;
	BOOST_TEST(a == b);
}
```

Also, I'm 90% sure the latter case did pass in the past (Boost 1.60 at least).

**Comment by Timmmm** [comment]
Do you happen to know what the fix is or which commit changed the behaviour?

**Comment by Timmmm** [comment]
Ah cool, I patched it like this and it works for us now:

```
inline assertion_result
compare_fpv( Lhs const& lhs, Rhs const& rhs, op::EQ<Lhs,Rhs>* )
{
    if (lhs == rhs) {
        return true;
    }
    ...
```

**Comment by raffienficiaud** [comment]
It is fixed on the branch `topic/GH-156-comparison-to-infinity`. However `close_at_tolerance` is using a tolerance value, and does not handle 0 nor infinity. I updated the doc as well.

Let me know if the branch works for you

**Comment by raffienficiaud** [comment]
In develop, thanks again for the report. Closing.

**Comment by Timmmm** [comment]
Seems like our tests have changed and I can't get them to fail now, but the fix looks good to me - thanks!

**Comment by raffienficiaud** [comment]
You're welcome!
