### ISSUE TITLE
Detecting boost_test_print_type does not work when testing a type with an explicit conversion to bool

### ISSUE THREAD

**Issue by marc-groundctl** [boostorg/test#158]
```cpp
struct s {
	explicit operator bool() const { return false; }
};
std::ostream &boost_test_print_type(std::ostream &o, const s &) { return o << 's'; }
```

When testing a value of type `s` (e.g. `BOOST_TEST(s{})`), compilation fails because the compiler is looking for an overload of `operator<<`, but we haven't provided one.  As per the documentation, providing a definition of `boost_test_print_type` should be sufficient.

**Comment by raffienficiaud** [comment]
See #159
