### ISSUE TITLE
Significant start slowdown on MSVC x64/Debug after upgrade to v1.68.0 

### ISSUE THREAD

**Issue by k15tfu** [boostorg/test#163]
Hi!

I'm experiencing a very bad problem:  I have a one boost test executable which contains over 50.000 test cases (data test cases mostly), and after upgrade to the latest Boost.Test the startup time has significantly increased from <3sec up to ~7min.

**Comment by raffienficiaud** [comment]
Can you post the test module (at least the init part)? I'll have a look

**Comment by k15tfu** [comment]
main.cpp
```
// BOOST_TEST_MODULE should:
// 1. be defined before any inclusion directive to Unit Test Framework headers
// 2. be defined exactly for one compilation unit of your test module
#define BOOST_TEST_MODULE Common

// Include header for `BOOST_TEST_MODULE`.
#include <boost/test/included/unit_test.hpp>
```

In other files we just include `boost/test/unit_test.hpp` and then define test cases by `BOOST_AUTO_TEST_CASE`. After that the main.o is linked together with foo_test.o (& Co.) into the mentioned .exe file.

**Comment by ww898** [comment]
Hi there,
I have the same issue in my project. My investigation shows that method `traverse_test_tree ()` works very slow. Most time it spends in `test_suite :: add()` on `BOOST_TEST_SETUP_ASSERT()` https://github.com/boostorg/test/blob/develop/include/boost/test/impl/test_tree.ipp#L248. The startup time increased in 2.5 times to 20min.

**Comment by ww898** [comment]
@raffienficiaud Well, I measured the execution time for one test which was chosen by the command line option `--run_test`:

| Configuration MSVC v14.13.26128 | 1.66.0 | 1.68.0 | in times slower |
|-|-:|-:|-:|
| Debug | 55s,048ms | 20m:50s,339ms | 22.71 |
| Release | 34s,174ms | 1m:43s,055ms | 3.01 |

**Comment by k15tfu** [comment]
Thank you guys for help!

**Comment by ww898** [comment]
@raffienficiaud Thank you very much for `topic/GH-163-slowdown-at-startup` branch:

| MSVC v14.13.26128 | boost v1.66.0 | boost v1.68.0 | boost v1.68.0 + branch |
|-|-:|-:|-:|
| Debug | 55s,048ms | 20m:50s,339ms | 53s,500ms |
| Release | 34s,174ms | 1m:43s,055ms | 34s,909ms  |

**Comment by raffienficiaud** [comment]
Merged to develop
