### ISSUE TITLE
Adding several test-suites with same name

### ISSUE THREAD

**Issue by raffienficiaud** [boostorg/test#164]
See https://svn.boost.org/trac10/ticket/12597

**Comment by gsauthof** [comment]
You wrote:

> I am not able to reproduce this problem of defining multiple test suites with same name with `BOOST_AUTO_TEST_SUITE`

What about defining test suites with the same name in different translation units with `BOOST_TEST_SUITE`  - is this supported/was this ever supported?

Apparently, this works for me with boost 1.64 but fails with recent boost versions:

    Test setup error: boost::unit_test::framework::setup_error:
        test unit with name 'somesuite' registered multiple times

**Comment by raffienficiaud** [comment]
Creating duplicate test suites with `BOOST_TEST_SUITE` was tolerated, but it was in fact creating 2 different test suites with the same name. This is not allowed any more. 

*However*, registering multiple times a test suite with `BOOST_AUTO_TEST_SUITE` with the same was always supported. Under the hood, this registration retrieves a suite with the same name - if any - or create a new one.

This logic is here: https://github.com/boostorg/test/blob/4df5b095eaa967f5e2687978bd3d9467b758f28e/include/boost/test/impl/test_tree.ipp#L468.

**Comment by raffienficiaud** [comment]
Closing, see rev https://github.com/gsauthof/libgrammar/commit/fe653ae3cfd10e4ec45436551d67c413fe561fc9
