### ISSUE TITLE
massive performance regression between 1.63 and 1.67

### ISSUE THREAD

**Issue by mgaunard** [boostorg/test#167]
Hi,

I haven't been able to bisect yet but I have observed a *massive* performance degradation between 1.63 and 1.67 when using a BOOST_DATA_TEST_CASE with an xrange of 100,000 values.

It takes 10 minutes just for the test system to initialize itself. It was instant before.

**Comment by raffienficiaud** [comment]
Thanks for the report. I believe this is a duplicate of #163. Solved already but not merged.
