### ISSUE TITLE
Compare collections of floating point values with tolerance

### ISSUE THREAD

**Issue by Flamefire** [boostorg/test#173]
Currently you can use **either**:

- `BOOST_TEST_REQUIRE( output == outputDesired, boost::test_tools::per_element() );`
- `BOOST_TEST_REQUIRE( output == outputDesired, boost::test_tools::tolerance( 1e-12f ) );`

But you cannot use both.

What is the preferred way to compare collections (e.g. vectors) of floating point values?

This is a common use case for testing numeric algorithms: Check results of optimized version vs. naive implementation.

**Comment by raffienficiaud** [comment]
What about using per-unit tolerance with a decorator?
https://www.boost.org/doc/libs/1_68_0/libs/test/doc/html/boost_test/utf_reference/testing_tool_ref/decorator_tolerance.html

**Comment by raffienficiaud** [comment]
@Flamefire there is a WIP branch for this: `topic/PR-187-BOOST_TEST-with-tolerance-message`: it would be nice if you can give a try until I polish it up. It should address this particular issue together with #242 and #187.

I'll try to make that for 1.73.

**Comment by raffienficiaud** [comment]
Merged to master.

**Comment by Char-Aznable** [comment]
@raffienficiaud  I struggle to find documentation on the OP's proposal. What exactly is the solution to this problem that get merged?

**Comment by raffienficiaud** [comment]
@Char-Aznable sorry for the late answer: now it is possible to combine both `boost::test_tools::per_element()` and `boost::test_tools::tolerance( 1e-12f )`. The documentation is only in the [change log](https://www.boost.org/doc/libs/1_78_0/libs/test/doc/html/boost_test/change_log.html#boost_test.change_log.boost_test_v3_13_boost_1_73) of 1.73.

If we need more, let me know I'll open a ticket.
