### ISSUE TITLE
High arity data test cases limit set by boost::bind() is much too low.

### ISSUE THREAD

**Issue by iolojz** [boostorg/test#175]
When having models with a large set of input parameters, one cannot use BOOST_DATA_TEST_CASE(). e.g in my case I need 12 input parameters.

It may be reasonable to not support binding of more than 9 arguments. But not supporting test cases with ten input parameters is not. One could e.g offer something like BOOST_DATA_TUPLE_TEST_CASE() that stuffs all arguments into a tuple and supplies that to the user.

**Comment by raffienficiaud** [comment]
Do you have a C++11 capable compiler?

**Comment by iolojz** [comment]
Yes, I do, but that is not the issue. From `test/data/test_case.hpp:162`...

    #if !defined(BOOST_TEST_DATASET_VARIADIC)
    // see BOOST_TEST_DATASET_MAX_ARITY to increase the default supported arity
    #define TC_MAKE(z,arity,_)                                                              \
    template<BOOST_PP_ENUM_PARAMS(arity, typename Arg)>                                 \
    void    operator()( BOOST_PP_ENUM_BINARY_PARAMS(arity, Arg, const& arg) ) const     \
    {                                                                                   \
        m_test_cases.push_back( new test_case( genTestCaseName(), m_tc_file, m_tc_line, \
           boost::bind( &TestCase::template test_method<BOOST_PP_ENUM_PARAMS(arity,Arg)>,\
           BOOST_PP_ENUM_PARAMS(arity, arg) ) ) );                                      \
    }                                                                                   \

    BOOST_PP_REPEAT_FROM_TO(1, BOOST_TEST_DATASET_MAX_ARITY, TC_MAKE, _)
    #else
    template<typename ...Arg>
    void    operator()(Arg&& ... arg) const
    {
        m_test_cases.push_back(
            new test_case( genTestCaseName(),
                           m_tc_file,
                           m_tc_line,
                           boost::bind( &TestCase::template test_method<Arg...>,
                                        boost_bind_rvalue_holder_helper(std::forward<Arg>(arg))...)));
    }
    #endif

The culprit is `boost::bind()` which is limited to nine parameters according to https://www.boost.org/doc/libs/1_68_0/libs/bind/doc/html/bind.html#bind.implementation.number_of_arguments.

**Comment by raffienficiaud** [comment]
Oh, right. There was a good reason for this: the forwarding of arguments was not working the same way for `boost::bind` and `std::bind` at the time I looked into this.
I'll have a look again.

**Comment by raffienficiaud** [comment]
Good new, this has been fixed in boost 1.67. Would you please check again?

**Comment by iolojz** [comment]
Indeed... My bad. I just checked it for thirty parameters and it works just fine. I am sorry, I had just blindly assumed I already had the latest version.
