### ISSUE TITLE
[snippet_dataset1_3] seems to be broken

### ISSUE THREAD

**Issue by green-anger** [boostorg/test#176]
There's a link to [snippet_dataset1_3]:
https://github.com/boostorg/test/blob/2b1e4cdda0c8526d9d2967d7e6fbe4818600283a/doc/test_organization/parametric_test_case_generation.qbk#L193-L196

Here is the snippet:
https://github.com/boostorg/test/blob/2b1e4cdda0c8526d9d2967d7e6fbe4818600283a/doc/snippet/dataset_1/test_file.cpp#L38-L44

But according to this
https://github.com/boostorg/test/blob/2b1e4cdda0c8526d9d2967d7e6fbe4818600283a/doc/test_organization/parametric_test_case_generation.qbk#L306-L310

the snippet must throw. And it does throw (msvc 19.15.26732.1 for x86 + boost.test 1.67.0).

So is it a broken snippet? I didn't find any mentions in the docs this to be intentional behavior.

**Comment by raffienficiaud** [comment]
Thanks you for raising this, and I agree that this is not the best way to communicate over Boost.Test features. 

I'll change the snippet for the next version.

**Comment by raffienficiaud** [comment]
Would this be ok? 1cd5487b32bf5fc0427aca5c4077f7d9525d6335
