### ISSUE TITLE
boost_check_equal-str-test failed on llvm

### ISSUE THREAD

**Issue by BinCaoWR** [boostorg/test#177]
Test log:
../libs/test/test/writing-test-ts/boost_check_equal-str-test.cpp(55): error: in "check_string_compare": check (void*)buf_ptr_cch != (void*)buf_array_cch has failed [0x800d3fd7 == 0x800d3fd7]

Test code:
char const* buf_ptr_cch     = "abc";
char const  buf_array_cch[] = "abc";
BOOST_TEST((void*)buf_ptr_cch != (void*)buf_array_cch);

Potential solution:
Add “<toolset>clang:<optimization>off” into boost.test-self-test() from libs/test/test/Jamfile.v2 to turn off the optimization for llvm. Verified the test can pass with this solution.

**Comment by raffienficiaud** [comment]
Please check the branch `topic/GH-177-boost_check_equal-str-test-failure`, it should be fixed there.

**Comment by raffienficiaud** [comment]
In master, closing. Thanks!
