### ISSUE TITLE
junit report: test error is also reported as failure

### ISSUE THREAD

**Issue by mistafunk** [boostorg/test#196]
Consider this snippet:

```
#define BOOST_TEST_MODULE Test1
#include <boost/test/included/unit_test.hpp>

BOOST_AUTO_TEST_CASE(testexception)
{
 throw 42;
}
```

Compiling and running above sample yields:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="0" skipped="0" errors="1" failures="1" id="0" name="Test1" time="0.000137">
<testcase assertions="1" name="testexception" time="0.000137">
```

Now, this is not so great. JUnit would report this as:

```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="0" skipped="0" errors="1" failures="0" id="0" name="Test1" time="0.000137">
<testcase assertions="1" name="testexception" time="0.000137">
```

Because according to JUnit a test either succeeds or fails (one or more assertion failures) or produces an error (unexpected failure). Boost on the other hand thinks that an error is also a failure.

Reproduced with Boost 1.66.0

**Comment by raffienficiaud** [comment]
If I understand well, as soon as there is an error, there is no failure? Can it happen that there are several errors?

**Comment by raffienficiaud** [comment]
I think I fixed this in branch `topic/GH-196-junit-abort-fail-not-same`. It would be good if you have a look to tell me if I understood the difference between `errors` and `failures` in the JUnit sense.

Thanks!

**Comment by mistafunk** [comment]
@raffienficiaud i understand junit report semantics like this:
* failure: an unsatisfied assert-like statement (typically within a test case), it follows there can be multiple failures per test case
* error: a runtime error in the test case (i.e. bad test case implementation)

to your questions:
* technically, there could be first a failed assert and then an unexpected/unhandled exception or segfault within a test case. junit discards any assertion results in a test case with implementation issues, i.e. an error.
* while there could be multiple implementation issues in a test case, the first one is usually sever enough and that's the error.

**Comment by mistafunk** [comment]
@raffienficiaud you branch looks fine

**Comment by raffienficiaud** [comment]
In master, closing.
