### ISSUE TITLE
Support BOOST_UNIT_TEST_FRAMEWORK_DYN_LINK et al

### ISSUE THREAD

**Issue by pdimov** [boostorg/test#198]
The CMake config files that `b2 install` installs automatically define `BOOST_${LIBNAME}_DYN_LINK=1` when the user links to the dynamic library $LIBNAME, by means of linking to the Boost::$libname target. This works most of the time, because the target/library name and the macro match, but doesn't for `Boost::unit_test_framework`, `Boost::test_exec_monitor` and `Boost::prg_exec_monitor`, because these use the macro `BOOST_TEST_DYN_LINK` and this doesn't match the target names.

So, would it be possible to make the libraries recognize their individual macros in addition to `BOOST_TEST_DYN_LINK`?

**Comment by raffienficiaud** [comment]
Currently building on the branch `topic/GH-198-support-boost-cmake-in-b2`. Would be good if you can give a try.

**Comment by pdimov** [comment]
I can confirm that without the fix, building https://github.com/boostorg/boost_install/tree/develop/test/test with `BUILD_SHARED_LIBS=ON` fails with link errors for missing `main`, but with the fix, it succeeds.

**Comment by raffienficiaud** [comment]
Very good, thanks for the feedback. Let's try to push that for 1.70.

**Comment by raffienficiaud** [comment]
In master, should be in 1.70.
