### ISSUE TITLE
Document required linker flags

### ISSUE THREAD

**Issue by NAThompson** [boostorg/test#201]
When using `BOOST_TEST_DYN_LINK`, the linker flag `-lboost_unit_test_framework` is not sufficient to successfully compile. Apparently there are more libraries that must be linked. For instance, when linking only with `-lboost_unit_test_framework`, I get the error:

```bash
Undefined symbols for architecture x86_64:
  "boost::unit_test::unit_test_log_t::instance()", referenced from:
      ___cxx_global_var_init in lanczos_smoothing_test-05d504.o
  "boost::unit_test::decorator::collector_t::instance()", referenced from:
      ___cxx_global_var_init.3 in lanczos_smoothing_test-05d504.o
  "boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector_t&, unsigned long)", referenced from:
      ___cxx_global_var_init.3 in lanczos_smoothing_test-05d504.o
ld: symbol(s) not found for architecture x86_64
clang: fatal error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by raffienficiaud** [comment]
Hi,

Thanks for the report. This might be related to the various issues that popped out when the visibility defaults have been changed on the build system.
Would it be possible for you to check if the branch `doc/various-updates-cleanups` is working as expected?

Thanks!

**Comment by raffienficiaud** [comment]
Thanks for the quick feedback, you did a lot of work!

The test `test/example/external_main_example_2.cpp` can work only for the shared version, so I would say this is normal. The CmakeLists.txt is for my own devs, so I am not expecting that it would work beyond simple use cases :) In particular, this is not mimicking the released version of boost.

Now that you are on this particular branch, what about compiling boost.test and then compile the unit test module you reported as failing?

I use this from the root folder (for OSX):
```
export current_version="1_70_0"
export build_folder=boost_${current_version}

./bootstrap.sh
./b2 \
  cflags="-mmacosx-version-min=10.10" \
  cxxflags="-std=c++11 -stdlib=libc++ -mmacosx-version-min=10.10" \
  mflags="-mmacosx-version-min=10.10" \
  mmflags="-mmacosx-version-min=10.10" \
  linkflags="-stdlib=libc++ -mmacosx-version-min=10.10" \
  --prefix=`pwd`/../${build_folder} \
  --without-log \
  --layout=versioned \
  install

```

Then, once compiled, you may try to recompile your own project againts boost.1.70 and report there.

Thanks!

**Comment by NAThompson** [comment]
Hi,

I have used your suggested syntax and successfully compiled, linked, and ran on top of your `doc/various-updates-cleanups` branch. So it appears that this issue has already been fixed, but the fixes didn't make it into 1.69? (Or maybe I'm still screwing up?) In any case, I'm satisfied with this outcome.

**Comment by raffienficiaud** [comment]
Thanks for the quick feedback. The changes will be there for 1.70 (merged this morning), there were many pending issues that couldn't solve in time for 1.69, sorry about that.

Closing.

**Comment by NAThompson** [comment]
Cool, thanks for your efforts. Looks like boost.test is really improving quickly!
