### ISSUE TITLE
Test cases with datasets and fixtures don't support flexible fixture interface.

### ISSUE THREAD

**Issue by dudamoos** [boostorg/test#203]
I have a fixture that I use for several of my tests that requires using the `setup()` and `teardown()` methods offered by the flexible fixture interface. I use `BOOST_FIXTURE_TEST_CASE` to declare my test cases so I can use members of this fixture class in my test code. This works fine when I use it for normal test cases, but when I try to use it for test cases with datasets (declared via `BOOST_DATA_TEST_CASE_F`), the `setup()` and `teardown()` methods don't get called, causing the test cases to crash. Looking at the code, I notice that the code to run test cases with datasets doesn't call `setup_conditional()` or `teardown_conditional()` like the normal fixture test case code does. That should be a trivial fix, and should help avoid surprises in the future.

**Comment by raffienficiaud** [comment]
Yes, I am aware of this one :) thanks for the reminder!

**Comment by raffienficiaud** [comment]
Yes, I am aware of this one :) thanks for the reminder!

**Comment by raffienficiaud** [comment]
In branch `topic/GH-203-dataset-new-fixtures` if you want to give a try.

**Comment by dudamoos** [comment]
That fix does the trick. I'll work on getting everyone here using an upgraded or patched version. Thanks!
