### ISSUE TITLE
BOOST_TEST_CHECK can't compare abstract classes using gcc

### ISSUE THREAD

**Issue by marc-groundctl** [boostorg/test#209]
```c++
struct abstract
{
    virtual ~abstract() = 0;
    bool operator==(const abstract &) const;
};

std::ostream &operator<<(std::ostream &, const abstract &);

void foo(abstract &a)
{
    BOOST_TEST_CHECK(a == a); // Fails
    BOOST_CHECK_EQUAL(a, a); // Works
}
```

[Godbolt](https://godbolt.org/z/00Y_Q3).  When compiling this code, GCC complains that it can't instantiate the member functions of `std::numeric_limits` with an abstract type.  Boost Test should check if `numeric_limits` is instantiable with a specific type before attempting to instantiate it; see https://stackoverflow.com/questions/16505782/determining-if-stdnumeric-limitst-is-safe-to-instantiate for a longer discussion of the issue and possible implementations.

**Comment by raffienficiaud** [comment]
I've made a fix, annoyingly the problem does not happen on clang/OSX. Waiting for CI checks.

**Comment by raffienficiaud** [comment]
Would it be possible for you to check the branch `topic/GH-209-BOOST_TEST-abstract-class-compare`. Right now it contains some failures on C++03 for comparing abstract classes (not sure I will be able to improve the support there) but otherwise seems to do the job.

**Comment by marc-groundctl** [comment]
That branch works for me.
