### ISSUE TITLE
Operands are not printed out when comparing 2 string_views

### ISSUE THREAD

**Issue by marc-groundctl** [boostorg/test#210]
```c++
BOOST_AUTO_TEST_CASE(strs)
{
	std::string str = "str";
	std::string_view sv = "sv";
	std::experimental::string_view sve = "sve";

	BOOST_TEST_CHECK(str != str);
	BOOST_TEST_CHECK(sv != sv);
	BOOST_TEST_CHECK(sve != sve);
}
```

This test prints out

```
x.cpp(13): error: in "strs": check str != str has failed [str == str]
x.cpp(14): error: in "strs": check sv != sv has failed
x.cpp(15): error: in "strs": check sve != sve has failed
```

Comparing 2 string_views should print out their contents when the comparison fails, just like it does with string.  Comparing a string_view with a string or a C string does print out its contents; this issue only occurs when comparing a string_view with another string_view.

**Comment by raffienficiaud** [comment]
Thanks for the report. In your example, why `std::experimental::string_view` ?

**Comment by marc-groundctl** [comment]
I was just seeing if it exhibited the same problem as `std::string_view`; I don't think supporting it is particularly important.

**Comment by raffienficiaud** [comment]
I have an implementation on the branch `topic/GH-210-comparing-string-views`. Should be out for 1.72 but it would be nice if you can give it a try.

**Comment by marc-groundctl** [comment]
Yeah, that branch works for me.
