### ISSUE TITLE
installing 1.70 on ubuntu 18.04

### ISSUE THREAD

**Issue by asdfzxh8** [boostorg/test#226]
sudo apt install libboost-dev would install the 1.65 version on ubuntu 18.04. Is that the newest version for the system?

I tried 
wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
tar -zxvf boost_1_70_0.tar.gz
cd boost_1_70_0/
./bootstrap.sh

but it showed 
'Building Boost.Build engine with toolset ... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details'?
Can anyone help? Thanks.

**Comment by raffienficiaud** [comment]
Maybe your system does not have the compiler installed? do you have gcc/g++ or clang/clang++ installed? Otherwise you can install a minimal compiler with `sudo apt-get install build-essential`

**Comment by asdfzxh8** [comment]
Thank you very much! After using your codes, the program got stuck at the next step:

root@ubuntutest:~/boost_1_70_0# ./b2
Performing configuration checks

    - default address-model    : 64-bit (cached)
    - default architecture     : x86 (cached)

Building the Boost C++ Libraries.


    - C++11 mutex              : yes (cached)
    - lockfree boost::atomic_flag : yes (cached)
    - Boost.Config Feature Check: cxx11_auto_declarations : yes (cached)
    - Boost.Config Feature Check: cxx11_constexpr : yes (cached)
    - Boost.Config Feature Check: cxx11_defaulted_functions : yes (cached)
    - Boost.Config Feature Check: cxx11_final : yes (cached)
    - Boost.Config Feature Check: cxx11_hdr_mutex : yes (cached)
    - Boost.Config Feature Check: cxx11_hdr_tuple : yes (cached)
    - Boost.Config Feature Check: cxx11_lambdas : yes (cached)
    - Boost.Config Feature Check: cxx11_noexcept : yes (cached)
    - Boost.Config Feature Check: cxx11_nullptr : yes (cached)
    - Boost.Config Feature Check: cxx11_rvalue_references : yes (cached)
    - Boost.Config Feature Check: cxx11_template_aliases : yes (cached)
    - Boost.Config Feature Check: cxx11_thread_local : yes (cached)
    - Boost.Config Feature Check: cxx11_variadic_templates : yes (cached)
    - has_icu builds           : no  (cached)
warning: Graph library does not contain MPI-based parallel components.
note: to enable them, add "using mpi ;" to your user-config.jam
    - zlib                     : no  (cached)
    - bzip2                    : no  (cached)
    - lzma                     : no  (cached)
    - zstd                     : no  (cached)
    - iconv (libc)             : yes (cached)
    - icu                      : no  (cached)
    - icu (lib64)              : no  (cached)
    - native-atomic-int32-supported : yes (cached)
    - native-syslog-supported  : yes (cached)
    - pthread-supports-robust-mutexes : yes (cached)
    - compiler-supports-ssse3  : yes (cached)
    - compiler-supports-avx2   : yes (cached)
    - gcc visibility           : yes (cached)
    - long double support      : yes (cached)
warning: skipping optional Message Passing Interface (MPI) library.
note: to enable MPI support, add "using mpi ;" to user-config.jam.
note: to suppress this message, pass "--without-mpi" to bjam.
note: otherwise, you can safely ignore this message.
warning: No python installation configured and autoconfiguration
note: failed.  See http://www.boost.org/libs/python/doc/building.html
note: for configuration instructions or pass --without-python to
note: suppress this message and silently skip all Boost.Python targets
    - libbacktrace builds      : yes (cached)
    - addr2line builds         : yes (cached)
    - WinDbg builds            : no  (cached)
    - WinDbgCached builds      : no  (cached)
    - BOOST_COMP_GNUC >= 4.3.0 : yes (cached)
    - zlib                     : no  (cached)
    - bzip2                    : no  (cached)
    - lzma                     : no  (cached)
    - zstd                     : no  (cached)

Component configuration:

    - atomic                   : building
    - chrono                   : building
    - container                : building
    - context                  : building
    - contract                 : building
    - coroutine                : building
    - date_time                : building
    - exception                : building
    - fiber                    : building
    - filesystem               : building
    - graph                    : building
    - graph_parallel           : building
    - headers                  : building
    - iostreams                : building
    - locale                   : building
    - log                      : building
    - math                     : building
    - mpi                      : building
    - program_options          : building
    - python                   : building
    - random                   : building
    - regex                    : building
    - serialization            : building
    - stacktrace               : building
    - system                   : building
    - test                     : building
    - thread                   : building
    - timer                    : building
    - type_erasure             : building
    - wave                     : building

...patience...
...patience...
...patience...
...patience...
...patience...
...patience...
...found 12386 targets...
...updating 1190 targets...
gcc.compile.c++ bin.v2/libs/wave/build/gcc-7.4.0/release/threading-multi/visibility-hidden/instantiate_cpp_exprgrammar.o

I see that all the memory of the instance is being used. I will probably upgrade the instance and try again.

**Comment by asdfzxh8** [comment]
It installed after upgrading the server instance. However, it still doesn't work:

The following directory should be added to compiler include paths:

    /root/boost_1_70_0

The following directory should be added to linker library paths:

    /root/boost_1_70_0/stage/lib

root@ubuntutest:~/boost_1_70_0# export INCLUDE="/root/boost_1_70_0:$INCLUDE"
root@ubuntutest:~/boost_1_70_0# export LIBRARY_PATH="/root/boost_1_70_0/stage/lib:$LIBRARY_PATH"
root@ubuntutest:~/boost_1_70_0# dpkg -s libboost-dev | grep Version
dpkg-query: package 'libboost-dev' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files,
and dpkg --contents (= dpkg-deb --contents) to list their contents.
