### ISSUE TITLE
warning: comparing floating point with == or != is unsafe [-Wfloat-equal]

### ISSUE THREAD

**Issue by jhasse** [boostorg/test#241]
When using `BOOST_CHECK_CLOSE` I'm getting the following warning:

```
boost/test/tools/floating_point_comparison.hpp:182:13: warning: comparing floating point with == or != is unsafe [-Wfloat-equal]
    if( (f1 == static_cast<FPT>(0)) ||
         ~~ ^  ~~~~~~~~~~~~~~~~~~~
```

Is there a way to silence this without me deactivating the warning completely?

**Comment by raffienficiaud** [comment]
Hi,

Thanks for the report, I've made a fix in the branch `topic/GH-241-floating-point-strict-comparison-warning`. Do you think you can give a try?

**Comment by jhasse** [comment]
Works! :)

**Comment by raffienficiaud** [comment]
Merged to master
