### ISSUE TITLE
 Could NOT find Boost (missing: unit_test_framework) (found version "1.71.0") 

### ISSUE THREAD

**Issue by Amjad95** [boostorg/test#244]
I need to use boost unit_test_framework, and what I am doing to find boost and the required libs is:
 find_package(Boost REQUIRED COMPONENTS unit_test_framework)
target_link_libraries (Boost_Tests_run Boost::unit_test_framework)
 I get this error: Could NOT find Boost (missing: unit_test_framework) (found version "1.71.0")
Note: I have built the boost libs!

What can I do to fix it?

**Comment by raffienficiaud** [comment]
@glenfe Thanks for transferring the issue here!

@Amjad95 I believe you found a resolution of this in https://github.com/boostorg/test/issues/240, I am closing the issue. Feel free to reopen if needed.
