### ISSUE TITLE
code coverity test defect

### ISSUE THREAD

**Issue by mozeat-sun** [boostorg/test#245]
hi
    will fix coverity issue ?
    scan boost 1.70.0 by Coverity ,report many issues,like bellow:
 
![image](https://user-images.githubusercontent.com/32629245/61845862-855a4c80-aed7-11e9-9268-a1636284a01f.png)

**Comment by raffienficiaud** [comment]
Thanks for reporting this, and sorry for the late reply (ticket was in the wrong place). The fix is easy and should go in for 1.73.

**Comment by mozeat-sun** [comment]
version: 1.70.0
 more:
![image](https://user-images.githubusercontent.com/32629245/72117883-3e2f1d80-338a-11ea-9b88-911533ba696c.png)
![image](https://user-images.githubusercontent.com/32629245/72117935-6ae33500-338a-11ea-936d-495cd7427a42.png)
@Raffi Enficiaud

**Comment by raffienficiaud** [comment]
The second post is not exactly related to Boost.Test but to Beat, it would be good if you post those images on the Beast project's issue tracker. Thanks!

**Comment by raffienficiaud** [comment]
Fixed in master for the issues related to boost/test. For the other issues, please contact @boostorg/beast team.
