### ISSUE TITLE
Incorect usage of BOOST_HEADER_DEPRECATED

### ISSUE THREAD

**Issue by Flamefire** [boostorg/test#246]
The use in e.g. https://github.com/boostorg/test/blob/741ff88f56ef88e4db995e5478c978447757db07/include/boost/test/floating_point_comparison.hpp#L14 should simply pass the new header as the argument. Otherwise the message is: 

> boost/test/floating_point_comparison.hpp:14:1: warning: This header is deprecated. Use This header is deprecated. Please use <boost/test/tools/floating_point_comparison.hpp> instead. instead. [-W#pragma-messages]

**Comment by raffienficiaud** [comment]
Fixed in master
