### ISSUE TITLE
Console colors are not restored on Windows

### ISSUE THREAD

**Issue by valiko-ua** [boostorg/test#254]
Failing tests set color to red and do not restore (on Windows), so that all subsequent output is red.

Program to reproduce:

```c++
#define BOOST_TEST_MODULE My Test
#include <boost/test/included/unit_test.hpp>
BOOST_AUTO_TEST_CASE(my_test)
{
    int i = 1;
    BOOST_TEST(i == 2);
    BOOST_TEST(i == 3);
}
```
![boost_test_bug_win](https://user-images.githubusercontent.com/13869060/75120442-baf52d00-5694-11ea-8c6d-3684e1afcf34.png)

**Comment by raffienficiaud** [comment]
Fix on branch `topic/GH-254-color-restored-windows`. Would be good if you give a try.

**Comment by valiko-ua** [comment]
I tested on Windows: commit https://github.com/boostorg/test/commit/63ab1f2bd67bb80ba8512a560fd42065295151c0 fixes this bug. Colors are restored.

**Comment by raffienficiaud** [comment]
Fixed in master
