### ISSUE TITLE
Is boost test thread safe?

### ISSUE THREAD

**Issue by jonesmz** [boostorg/test#304]
I see no documentation about threads anywhere in https://www.boost.org/doc/libs/1_75_0/libs/test/doc/html/index.html

I am also failing to find references to thread safety by searching the code here in github.

Should I expect this code to work?

```cpp
BOOST_TEXT_CASE(test_parallel)
{
    std::vector<std::string> vect(1024u);
    std::for_each(
        std::execution::par_unseq,
        vect.begin(),
        vect.end(),
        [](auto const& str)
        {
            BOOST_CHECK_EQUAL(str, "");
        });
}
```
?

**Comment by jonesmz** [comment]
Hi. This is hopefully a simple question to answer.

Is BOOST_TEST thread safe or not?

**Comment by jonesmz** [comment]
This is a very simple question.

Can no project member answer it?

**Comment by raffienficiaud** [comment]
Boost.Test is currently not thread safe.

**Comment by jonesmz** [comment]
Can that be clearly documented in the manual then?

https://www.boost.org/doc/libs/1_76_0/libs/test/doc/html/boost_test/section_faq.html <-

**Comment by raffienficiaud** [comment]
In branch `topic/doc-update`

**Comment by raffienficiaud** [comment]
Merged in https://github.com/boostorg/test/pull/337 rev https://github.com/boostorg/test/commit/b52b0ea6429c393485f8ea27ab5edd678823e65a.
