### ISSUE TITLE
boost test documentation tells users to file bugs with decommissioned Trac.

### ISSUE THREAD

**Issue by jonesmz** [boostorg/test#305]
https://www.boost.org/doc/libs/1_75_0/libs/test/doc/html/boost_test/section_faq.html
```
I found a bug. Where can I report it?

You can send a bug report to the boost users' mailing list and/or fill a ticket here https://svn.boost.org/trac/boost/. 
```

**Comment by jonesmz** [comment]
That's not the problem...

The problem is that the documentation for the library is telling users to make bug reports on a bug tracker that is no longer used.

**Comment by rdoeffinger** [comment]
That documentation is actually part of this repo: https://github.com/boostorg/test/blob/develop/doc/closing_chapters/faq.qbk
Maybe a pull request would get it addressed faster?

**Comment by jonesmz** [comment]
But what should the change actually be? File bugs on github?

**Comment by raffienficiaud** [comment]
Merged in https://github.com/boostorg/test/pull/337 rev https://github.com/boostorg/test/commit/b52b0ea6429c393485f8ea27ab5edd678823e65a.

**Comment by rdoeffinger** [comment]
There seems to be a typo in the merged README.md, it says BOOST_TEXT_CASE where it should be BOOST_TEST_CASE I think?
