### ISSUE TITLE
This compiles: `BOOST_TEST(1 = somestring.size());`

### ISSUE THREAD

**Issue by zethon** [boostorg/test#312]
The following code compiles when using unit_test.hpp

```
BOOST_TEST(1 = somestring.size());
```

The code does fail to compile when using lightweight_test.hpp.

See: https://gcc.godbolt.org/z/MT8xrdesh

**Comment by raffienficiaud** [comment]
`lightweight_test.hpp` is not part of Boost.Test.

**Comment by zethon** [comment]
> lightweight_test.hpp is not part of Boost.Test.

That's fine, but the bug is in unit_test.hpp. The could I pasted **should not** compile.

**Comment by zethon** [comment]
*bump* ?
